export const GET_INBOX_SAVES_START = "GET_INBOX_SAVES_START";
export const GET_INBOX_SAVES_SUCCESS = "GET_INBOX_SAVES_SUCCESS";
export const GET_INBOX_SAVES_ERRORS = "GET_INBOX_SAVES_ERRORS";

export const GET_INBOX_DRAFTS_START = "GET_INBOX_DRAFTS_START";
export const GET_INBOX_DRAFTS_SUCCESS = "GET_INBOX_DRAFTS_SUCESS";
export const GET_INBOX_DRAFTS_ERRORS = "GET_INBOX_DRAFTS_ERRORS";


export const GET_INBOX_ARCHIVES_START = "GET_INBOX_ARCHIVES_START";
export const GET_INBOX_ARCHIVES_SUCCESS = "GET_INBOX_ARCHIVES_SUCCESS";
export const GET_INBOX_ARCHIVES_ERRORS = "GET_INBOX_ARCHIVES_ERRORS";
